# Generated by Django 4.2.7 on 2023-11-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rename_designs_design_design_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='design',
        ),
        migrations.AddField(
            model_name='design',
            name='designs',
            field=models.ManyToManyField(related_name='designs', to='Core.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Design'),
        ),
    ]
