# Generated by Django 4.2.7 on 2023-11-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_post_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.post'),
        ),
    ]
