# Generated by Django 4.2.7 on 2023-11-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_image_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
