# Generated by Django 4.2.7 on 2023-11-21 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_post_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_type',
            field=models.CharField(choices=[('process', 'Process'), ('completed', 'Complete')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
