# Generated by Django 4.2.7 on 2023-11-21 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_rename_project_design_design_remove_design_designs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_flow',
            field=models.CharField(choices=[('process', 'Process'), ('completed', 'Complete')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='project_type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], max_length=50),
        ),
    ]
