# Generated by Django 4.2.7 on 2023-11-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_post_project_flow_alter_post_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='Core.post'),
        ),
    ]
