# Generated by Django 4.2.7 on 2023-11-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_design_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='design',
            new_name='post',
        ),
    ]
