# Generated by Django 4.2.7 on 2023-11-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_rename_design_design_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='post',
            new_name='design',
        ),
    ]
