# Generated by Django 4.2.7 on 2023-11-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0018_alter_design_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_cover',
            field=models.ImageField(default=0, upload_to='Design/Covers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_design', to='Core.post'),
        ),
    ]
