# Generated by Django 4.2.7 on 2023-11-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0019_post_project_cover_alter_design_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(upload_to='Design/Gallery')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_gallery', to='Core.post')),
            ],
        ),
    ]
