# Generated by Django 4.2.7 on 2023-11-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0022_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='figma_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='linkdin_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
