# Generated by Django 4.2.7 on 2023-11-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0023_post_figma_link_post_linkdin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='github_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
