# Generated by Django 4.2.7 on 2023-11-26 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0024_alter_post_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='project_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Design/Logos'),
            preserve_default=False,
        ),
    ]
